local:
  url: http://some-site.loft
  location: ITLS
  basepath: /path/to/dev/branch/site
  role: dev
  copy_source:
    0: web/.htaccess
    1: web/sites/default/settings.local.php
    2: web/sites/default/settings.local.php
  copy_local_to:
    0: install/default/.htaccess.dev
    1: install/default/settings.local.dev.php
    2: private/default/secrets.dev.php
  copy_production_to:
    0: install/default/.htaccess.prod
    1: install/default/settings.local.prod.php
    2: private/default/secrets.prod.php
  copy_staging_to:
    0: install/default/.htaccess.staging
    1: install/default/settings.local.staging.php
    2: private/default/secrets.staging.php
  files:
    0: web/sites/default/files
    1: private/default/files
  database:
    backups: private/default/db/purgeable
  drupal:
    root: web
    settings: web/sites/default/settings.php
    database: default
production:
  config: /var/www/some-site/.loft_deploy
  script: /usr/local/bin/loft_deploy
  user: username
  host: NNN.NNN.NNN.NNN
staging:
  config: /var/www/some-site/.loft_deploy
  script: /usr/local/bin/loft_deploy
  user: username
  host: NNN.NNN.NNN.NNN

