local:
  url: https://some-site.com
  location: Acquia
  basepath: /path/to/prod/branch
  role: prod
  copy_source:
    0: web/.htaccess
    1: web/sites/default/settings.local.php
    2: web/sites/default/settings.local.php
  files:
    0: web/sites/default/files
    1: private/default/files
  database:
    backups: private/default/db/purgeable
  drupal:
    root: web
    settings: web/sites/default/settings.php
    database: default
