#!/bin/bash
#
# @file
# Configuration file for loft_deploy for a production environment
#

##
 # LOCAL CONFIGURATION (For Production)
 #

local_role="prod"

# Where are your non-versioned, dynamic files kept?
local_files='/home/loftuber/intheloftstudios/public_html/sites/default/files'

# Where do you want db dumps saved?
local_db_dir='/home/loftuber/intheloftstudios/releases/current/db/tags'

# What are the credentials for connecting to the database?
local_db_host='mysql-itl.intheloftstudios.com'
local_db_name='itl_drupal'
local_db_user='loftuber'
local_db_pass='oPjYQGvmwB2Xnrp3W48DfqMt'

##
 # END LOCAL CONFIGURATION
 #










#!/bin/bash
#
# @file
# Configuration file for loft_deploy for a local development environment
#

##
 # LOCAL CONFIGURATION (For Local Development)
 #

local_role="local"

# Where are your non-versioned, dynamic files kept?
local_files='/Library/WebServer/Documents/intheloftstudios/public_html/sites/default/files'

# Where do you want db dumps saved?
local_db_dir='/Library/WebServer/Documents/intheloftstudios/db/tags/'

# What are the credentials for connecting to the database?
local_db_host='localhost'
local_db_name='itl_drupal_loft'
local_db_user='loft'
local_db_pass='dloft9'

##
 # END LOCAL CONFIGURATION
 #

##
 # PRODUCTION CONFIGURATION
 #
production_server='loftuber@intheloftstudios.com'
production_db_name='itl_drupal'
production_files='/home/loftuber/intheloftstudios/public_html/sites/default/files'
production_db_dir='/home/loftuber/intheloftstudios/releases/current/db/tags'
production_db_tag='/home/loftuber/intheloftstudios/releases/current/db/tags/tags.sh'

##
 # END PRODUCTION CONFIGURATION
 #
