#!/bin/bash
#
# @file
# Configuration file for loft_deploy for a production environment
#

##
 # LOCAL CONFIGURATION (For Production)
 #

local_role="prod"

# Where are your non-versioned, dynamic files kept?
local_files='path/to/prod_branch/public_html/sites/default/files'

# Where do you want db dumps saved?
local_db_dir='path/to/prod_branch/releases/current/db/tags'

# What are the credentials for connecting to the database?
#local_db_host='localhost'
local_db_name='prod_db_name'
local_db_user='prod_db_user'
local_db_pass='prod_db_password'

##
 # END LOCAL CONFIGURATION
 #









