#!/bin/bash
#
# @file
# Configuration file for loft_deploy for a local development environment
#
ld_mysql='/Applications/MAMP/Library/bin/mysql'
ld_mysqldump='/Applications/MAMP/Library/bin/mysqldump'
ld_gzip='/usr/bin/gzip'
ld_gunzip='/usr/bin/gunzip'

##
 # LOCAL CONFIGURATION (For Development)
 #

local_role="dev"

# An arbitrary title describing this environment to you for personal id; the
# provided format is a suggestion, any is valid
local_title="Host Company or Location ~ local url"

# Where do you want db dumps saved?
local_db_dir='/Library/WebServer/Documents/path/to/dev/branch/site/db/tags'

# Optional, where are your non-versioned, dynamic files kept?
local_files='/Library/WebServer/Documents/path/to/dev/branch/site/public_html/sites/default/files'

# What are the credentials for connecting to the database?
#local_db_host='localhost'
local_db_name='dev_db_name'
local_db_user='dev_db_user'
local_db_pass='dev_db_pass'

##
 # END LOCAL CONFIGURATION
 #

##
 # PRODUCTION CONFIGURATION
 #
#production_script='~/bin/loft_deploy'
production_server='prod_user@prod_host'
production_pass='prod_pass'
# production_root is parent directory of .loft_deploy
production_root='path/to/prod_branch/'
production_db_name='prod_db_name'
production_db_dir='path/to/prod_branch/releases/current/db/tags'
# production_files is optional
production_files='path/to/prod_branch/public_html/sites/default/files'

##
 # END PRODUCTION CONFIGURATION
 #

##
 # STAGING SERVER
 #
staging_script='~/bin/loft_deploy'
staging_server='staging_user@staging_host'
staging_pass='staging_pass'
#staging_root is parent directory of .loft_deploy
staging_root='path/to/staging_branch/'
staging_files='path/to/staging_branch/public_html/sites/default/files'
staging_db_dir='path/to/staging_branch/releases/current/db/tags'

##
 # END STAGING CONFIGURATION
 #
