local:
  url: https://some-site.com
  location: Acquia
  basepath: /path/to/prod/branch
  role: prod
  copy_source:
  - web/.htaccess
  - web/sites/default/settings.local.php
  - web/sites/default/settings.local.php
  files:
  - web/sites/default/files
  - private/default/files
  database:
    backups: private/default/db/purgeable
  drupal:
    root: web
    settings: web/sites/default/settings.php
    database: default
