#!/bin/bash
#
# @file
# Configuration file for loft_deploy for a production environment
#

##
 # LOCAL CONFIGURATION (For Production)
 #

local_role="prod"

# An arbitrary title describing this environment to you for personal id; the
# provided format is a suggestion, any is valid
local_title="Host Company or Location ~ local url"

# Where are your non-versioned, dynamic files kept?
local_files='path/to/prod_branch/web/sites/default/files'

# Where do you want db dumps saved?
local_db_dir='path/to/prod_branch/releases/current/db/tags'

# What are the credentials for connecting to the database?
#local_db_host='localhost'
local_db_name='prod_db_name'
local_db_user='prod_db_user'
local_db_pass='prod_db_password'

# Alternately to the credentials declaration above, if this is Drupal just point to the settings.php file
#local_drupal_root='/some/path/drupal/webroot'
#local_drupal_settings='/some/path/to/settings.php'
#local_drupal_db='default'

##
 # END LOCAL CONFIGURATION
 #
