local:
  url: https://stage.some-site.com
  location: Acquia
  basepath: /path/to/staging/branch
  role: staging
  files:
    - web/sites/default/files
    - private/default/files
  database:
    backups: private/default/db/purgeable
  drupal:
    root: web
    settings: web/sites/default/settings.php
    database: default
