#!/usr/bin/php
<?php

/**
 * @file
 * Write a bash config file based on JSON.
 *
 * This is the second step in the configuration compiling.
 *
 * @group configuration
 * @see config_to_json.php
 */

use AKlump\LoftLib\Bash\Configuration;

require_once __DIR__ . '/bootstrap.php';

$namespace = $argv[2];
$json = $argv[3];

$var_service = new Configuration($namespace, '.');

try {
  if (empty($json)) {
    throw new \RuntimeException("JSON is empty; cannot parse an empty configuration string.");
  }
  $data = json_decode($json, TRUE);
  if ($data === NULL) {
    throw new \RuntimeException("Invalid JSON: \"$json\"");
  }

  $context = ['stack' => []];
  $context['stack'][] = "#!/usr/bin/env bash\n";
  $context['stack'][] = "#\n# @file\n# Autogenerated configuration; DO NOT EDIT.\n#\n";
  $stack = $var_service->flatten($data, $context);
  echo implode(PHP_EOL, $stack);
  exit(0);

}
catch (\Exception $exception) {
  $exception->getMessage();
}

exit(1);
